import { expect, test } from '@playwright/test';

test('Mobile Ghost Test', async ({ page }) => {
    // TODO: Refactor all e2e tests to use explicit waits for reliability
    console.log('Navigating to login page');
    await page.goto('/login');
    console.log('Filling in login credentials');
    await expect(page.getByRole('textbox', { name: 'Email address' })).toBeVisible();
    await page.getByRole('textbox', { name: 'Email address' }).click();
    await page.getByRole('textbox', { name: 'Email address' }).fill('superadmin@e2e.test');
    await expect(page.getByRole('textbox', { name: 'Password' })).toBeVisible();
    await page.getByRole('textbox', { name: 'Password' }).click();
    await page.getByRole('textbox', { name: 'Password' }).fill('superadminpassword');
    await expect(page.getByRole('checkbox', { name: 'Remember me' })).toBeVisible();
    await page.getByRole('checkbox', { name: 'Remember me' }).click();
    console.log('Clicking Log in');
    await expect(page.getByRole('button', { name: 'Log in' })).toBeVisible();
    await page.getByRole('button', { name: 'Log in' }).click();
    console.log('Navigating through admin menu');
    await expect(page.getByText('AdministrationClick to select')).toBeVisible();
    await page.getByText('AdministrationClick to select').click();
    await expect(page.getByRole('button', { name: 'Toggle Sidebar' })).toBeVisible();
    await page.getByRole('button', { name: 'Toggle Sidebar' }).click();
    await expect(page.getByRole('link', { name: 'Users' })).toBeVisible();
    await page.getByRole('link', { name: 'Users' }).click();
    await expect(page.getByRole('link', { name: 'Create User' })).toBeVisible();
    await page.getByRole('link', { name: 'Create User' }).click();
    await expect(page.getByRole('link', { name: 'Users' })).toBeVisible();
    await page.getByRole('link', { name: 'Users' }).click();
    await expect(page.getByRole('button', { name: 'Toggle Sidebar' })).toBeVisible();
    await page.getByRole('button', { name: 'Toggle Sidebar' }).click();
    await expect(page.getByRole('link', { name: 'Organizations' })).toBeVisible();
    await page.getByRole('link', { name: 'Organizations' }).click();
    await expect(page.getByRole('button', { name: 'View' })).toBeVisible();
    await page.getByRole('button', { name: 'View' }).click();
    await expect(page.getByRole('menuitemcheckbox', { name: 'name' })).toBeVisible();
    await page.getByRole('menuitemcheckbox', { name: 'name' }).click();
    await expect(page.getByRole('link', { name: 'Create Organization' })).toBeVisible();
    await page.getByRole('link', { name: 'Create Organization' }).click();
    await expect(page.getByRole('button', { name: 'Toggle Sidebar' })).toBeVisible();
    await page.getByRole('button', { name: 'Toggle Sidebar' }).click();
    await expect(page.getByRole('button', { name: 'Super Admin' })).toBeVisible();
    await page.getByRole('button', { name: 'Super Admin' }).click();
    await expect(page.getByRole('menuitem', { name: 'Settings' })).toBeVisible();
    await page.getByRole('menuitem', { name: 'Settings' }).click();
    await expect(page.getByRole('link', { name: 'Password' })).toBeVisible();
    await page.getByRole('link', { name: 'Password' }).click();
    await expect(page.getByRole('link', { name: 'Appearance' })).toBeVisible();
    await page.getByRole('link', { name: 'Appearance' }).click();
    console.log('Switching appearance modes');
    await expect(page.getByRole('button', { name: 'Dark' })).toBeVisible();
    await page.getByRole('button', { name: 'Dark' }).click();
    await expect(page.getByRole('button', { name: 'System' })).toBeVisible();
    await page.getByRole('button', { name: 'System' }).click();
    await expect(page.getByRole('link', { name: 'Back to Home' })).toBeVisible();
    await page.getByRole('link', { name: 'Back to Home' }).click();
    console.log('Logging out');
    await expect(page.getByRole('button', { name: 'Log out' })).toBeVisible();
    await page.getByRole('button', { name: 'Log out' }).click();
});
