name: tests

on:
  pull_request:
  workflow_call:

jobs:
  backend-and-fullstack-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Create SQLite Database
        run: touch database/database.sqlite

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Publish Ziggy Configuration
        run: php artisan ziggy:generate

      - name: Build Assets
        run: npm run build

      - name: Run Vitest
        run: npx vitest run
        env:
          LARAVEL_BYPASS_ENV_CHECK: 1

      - name: SCA Tests
        run: ./vendor/bin/phpstan analyse

      - name: Pest Tests
        run: ./vendor/bin/pest --ci --coverage --min=100

      - name: Type Coverage Tests
        run: ./vendor/bin/pest --type-coverage

      - name: Mutation Tests
        run: ./vendor/bin/pest --mutate --min=100 --ignore-min-score-on-zero-mutations
